services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:public
    restart: unless-stopped
    hostname: pc-audunn
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=IS
      - PLEX_CLAIM=claim-AHzXJSSLFzzA3AL2bUv7
      - ADVERTISE_IP=http://192.168.1.147:32400/
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - ~/plex/config:/config     
      - ~/plex/transcode:/transcode
      - /mnt/e/media:/data